CREATE TABLE [dbo].[OrleansQuery](
	[QueryKey] [varchar](64) NOT NULL,
	[QueryText] [varchar](8000) NOT NULL,
 CONSTRAINT [OrleansQuery_Key] PRIMARY KEY CLUSTERED 
(
	[QueryKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
